#!/usr/bin/env bash

edit_path=true

if [ -d ~/.termex ]
then
    echo "Termex is already installed!"
    read -p "Update? [Y|n]" -n 1 -s update < /dev/tty
    echo ""
    
    if [ ! "$update" == "n" ]
    then
        ~/.termex/updater
        exit
    fi
    
    edit_path=false
fi

[ -d ~/.termex ] && rm -dfr ~/.termex

git clone https://github.com/stefanwimmer128/termex.git ~/.termex -q || exit
cd ~/.termex

tags=( $(git tag) )
git checkout tags/${tags[$(( ${#tags[@]}-1 ))]} -q || exit

if [ "$edit_path" == "true" ]
then
    cat ~/.bashrc > "$(mktemp -p ~ .bashrc.XXXX)"
    echo -e "\n[ -d ~/.termex ] && [ -d ~/.termex/bin ] && export PATH=\"\$PATH:\$(readlink -f ~/.termex/bin)\"" >> ~/.bashrc
fi

unset edit_path
unset tags

echo "Installation successful!"
