#!/usr/bin/env bash

TERMEX_DIR="$(dirname "$(readlink -f "${argv[0]:-$0}")")"

if [ -z "$TERMEX" ]
then
    "$TERMEX_DIR/bin/termex" "$TERMEX_DIR/update"
fi

cd "$TERMEX_DIR"

git fetch || die "git fetch error"

git checkout $(git describe --tags $(git rev-list --tags --max-count=1)) || "git checkout error"
